ALTER TABLE "staff" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "manufacturer" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "procedure" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "bom" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "bomLine" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "het" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "workflow" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "phase" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "phaseEquip" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "workOrder" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "woSerial" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "sterilise" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "printLabel" ALTER COLUMN "tenantId" SET DEFAULT 'ventas', ALTER COLUMN "tenantId" SET NOT NULL;

DROP INDEX IF EXISTS "workflow_code_key";
CREATE UNIQUE INDEX "workflow_tenantId_code_key" ON "workflow"("tenantId", "code");

ALTER TABLE "staff" ADD CONSTRAINT "staff_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "manufacturer" ADD CONSTRAINT "manufacturer_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "procedure" ADD CONSTRAINT "procedure_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "bom" ADD CONSTRAINT "bom_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "bomLine" ADD CONSTRAINT "bomLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "het" ADD CONSTRAINT "het_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "workflow" ADD CONSTRAINT "workflow_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "phase" ADD CONSTRAINT "phase_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "phaseEquip" ADD CONSTRAINT "phaseEquip_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "workOrder" ADD CONSTRAINT "workOrder_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "woSerial" ADD CONSTRAINT "woSerial_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sterilise" ADD CONSTRAINT "sterilise_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "printLabel" ADD CONSTRAINT "printLabel_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "supplyEntity" ADD CONSTRAINT "supplyEntity_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionPoint" ADD CONSTRAINT "collectionPoint_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionPoint" ADD CONSTRAINT "collectionPoint_supplyEntityId_fkey" FOREIGN KEY ("supplyEntityId") REFERENCES "supplyEntity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionUnit" ADD CONSTRAINT "collectionUnit_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionUnit" ADD CONSTRAINT "collectionUnit_supplyEntityId_fkey" FOREIGN KEY ("supplyEntityId") REFERENCES "supplyEntity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "collectionUnit" ADD CONSTRAINT "collectionUnit_collectionPointId_fkey" FOREIGN KEY ("collectionPointId") REFERENCES "collectionPoint"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "issuanceOrder" ADD CONSTRAINT "issuanceOrder_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "issuanceOrder" ADD CONSTRAINT "issuanceOrder_supplyEntityId_fkey" FOREIGN KEY ("supplyEntityId") REFERENCES "supplyEntity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "issuanceOrder" ADD CONSTRAINT "issuanceOrder_collectionPointId_fkey" FOREIGN KEY ("collectionPointId") REFERENCES "collectionPoint"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "issuanceOrderLine" ADD CONSTRAINT "issuanceOrderLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "issuanceOrderLine" ADD CONSTRAINT "issuanceOrderLine_issuanceOrderId_fkey" FOREIGN KEY ("issuanceOrderId") REFERENCES "issuanceOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "issuanceOrderLine" ADD CONSTRAINT "issuanceOrderLine_collectionUnitId_fkey" FOREIGN KEY ("collectionUnitId") REFERENCES "collectionUnit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "collectionUnitFulfilment" ADD CONSTRAINT "collectionUnitFulfilment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionUnitFulfilment" ADD CONSTRAINT "collectionUnitFulfilment_collectionUnitId_fkey" FOREIGN KEY ("collectionUnitId") REFERENCES "collectionUnit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "collectionOrder" ADD CONSTRAINT "collectionOrder_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionOrder" ADD CONSTRAINT "collectionOrder_supplyEntityId_fkey" FOREIGN KEY ("supplyEntityId") REFERENCES "supplyEntity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "collectionOrder" ADD CONSTRAINT "collectionOrder_collectionPointId_fkey" FOREIGN KEY ("collectionPointId") REFERENCES "collectionPoint"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "collectionReceipt" ADD CONSTRAINT "collectionReceipt_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionReceipt" ADD CONSTRAINT "collectionReceipt_collectionOrderId_fkey" FOREIGN KEY ("collectionOrderId") REFERENCES "collectionOrder"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "collectionReceiptLine" ADD CONSTRAINT "collectionReceiptLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collectionReceiptLine" ADD CONSTRAINT "collectionReceiptLine_collectionReceiptId_fkey" FOREIGN KEY ("collectionReceiptId") REFERENCES "collectionReceipt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "collectionReceiptLine" ADD CONSTRAINT "collectionReceiptLine_collectionUnitId_fkey" FOREIGN KEY ("collectionUnitId") REFERENCES "collectionUnit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "procurementImportReport" ADD CONSTRAINT "procurementImportReport_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
